"""add import source tracking

Revision ID: 00365cb2682e
Revises: b7be459dc4eb
Create Date: 2026-07-29 14:31:07.306565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00365cb2682e'
down_revision: Union[str, Sequence[str], None] = 'b7be459dc4eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imports', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('imports', sa.Column('source_type', sa.String(), nullable=False))
    op.create_foreign_key(None, 'imports', 'users', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'imports', type_='foreignkey')
    op.drop_column('imports', 'source_type')
    op.drop_column('imports', 'created_by_id')
    # ### end Alembic commands ###
