"""add campaign relation to imports

Revision ID: e3b6b67a7145
Revises: 00365cb2682e
Create Date: 2026-07-29 14:50:53.399180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3b6b67a7145'
down_revision: Union[str, Sequence[str], None] = '00365cb2682e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imports', sa.Column('campaign_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'imports', 'campaigns', ['campaign_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'imports', type_='foreignkey')
    op.drop_column('imports', 'campaign_id')
    # ### end Alembic commands ###
